name: 'Leaked Secrets Scan'

on:
  pull_request:

jobs:
  scan:
    name: leaked-secrets-alert
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - uses: lux-group/infra-github-actions/leaked-secrets-alert@1.4.0
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
